// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx5v4LQkio35nV5oCk_4XK1KNGZvWcN5M',
    appId: '1:315402389325:web:e0918f477e4003efa6d904',
    messagingSenderId: '315402389325',
    projectId: 'campusconnect-0',
    authDomain: 'campusconnect-0.firebaseapp.com',
    storageBucket: 'campusconnect-0.firebasestorage.app',
    measurementId: 'G-KNSG636LX9',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAQd62lkUc5HRWmet_KOr_toZ3UCYQmaM',
    appId: '1:315402389325:android:3802f8bd3a603e18a6d904',
    messagingSenderId: '315402389325',
    projectId: 'campusconnect-0',
    storageBucket: 'campusconnect-0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFqTWl3MhZ8typzAEK14eX1U9sNs9K7ks',
    appId: '1:315402389325:ios:fd31fe2020108a6ea6d904',
    messagingSenderId: '315402389325',
    projectId: 'campusconnect-0',
    storageBucket: 'campusconnect-0.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFqTWl3MhZ8typzAEK14eX1U9sNs9K7ks',
    appId: '1:315402389325:ios:fd31fe2020108a6ea6d904',
    messagingSenderId: '315402389325',
    projectId: 'campusconnect-0',
    storageBucket: 'campusconnect-0.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx5v4LQkio35nV5oCk_4XK1KNGZvWcN5M',
    appId: '1:315402389325:web:c1621cf8566b6beea6d904',
    messagingSenderId: '315402389325',
    projectId: 'campusconnect-0',
    authDomain: 'campusconnect-0.firebaseapp.com',
    storageBucket: 'campusconnect-0.firebasestorage.app',
    measurementId: 'G-7E23Z1KHZM',
  );
}
